/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PixTransactionIdRouteImport } from './routes/pix.$transactionId'
import { Route as ApiPublicParadiseWebhookRouteImport } from './routes/api/public/paradise-webhook'
import { Route as ApiPublicOrderStatusRouteImport } from './routes/api/public/order-status'
import { Route as ApiPublicCreatePixRouteImport } from './routes/api/public/create-pix'

const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PixTransactionIdRoute = PixTransactionIdRouteImport.update({
  id: '/pix/$transactionId',
  path: '/pix/$transactionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicParadiseWebhookRoute =
  ApiPublicParadiseWebhookRouteImport.update({
    id: '/api/public/paradise-webhook',
    path: '/api/public/paradise-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOrderStatusRoute = ApiPublicOrderStatusRouteImport.update({
  id: '/api/public/order-status',
  path: '/api/public/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreatePixRoute = ApiPublicCreatePixRouteImport.update({
  id: '/api/public/create-pix',
  path: '/api/public/create-pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/pix/$transactionId': typeof PixTransactionIdRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/paradise-webhook': typeof ApiPublicParadiseWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/pix/$transactionId': typeof PixTransactionIdRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/paradise-webhook': typeof ApiPublicParadiseWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/obrigado': typeof ObrigadoRoute
  '/pix/$transactionId': typeof PixTransactionIdRoute
  '/api/public/create-pix': typeof ApiPublicCreatePixRoute
  '/api/public/order-status': typeof ApiPublicOrderStatusRoute
  '/api/public/paradise-webhook': typeof ApiPublicParadiseWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/obrigado'
    | '/pix/$transactionId'
    | '/api/public/create-pix'
    | '/api/public/order-status'
    | '/api/public/paradise-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/obrigado'
    | '/pix/$transactionId'
    | '/api/public/create-pix'
    | '/api/public/order-status'
    | '/api/public/paradise-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/obrigado'
    | '/pix/$transactionId'
    | '/api/public/create-pix'
    | '/api/public/order-status'
    | '/api/public/paradise-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PixTransactionIdRoute: typeof PixTransactionIdRoute
  ApiPublicCreatePixRoute: typeof ApiPublicCreatePixRoute
  ApiPublicOrderStatusRoute: typeof ApiPublicOrderStatusRoute
  ApiPublicParadiseWebhookRoute: typeof ApiPublicParadiseWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix/$transactionId': {
      id: '/pix/$transactionId'
      path: '/pix/$transactionId'
      fullPath: '/pix/$transactionId'
      preLoaderRoute: typeof PixTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paradise-webhook': {
      id: '/api/public/paradise-webhook'
      path: '/api/public/paradise-webhook'
      fullPath: '/api/public/paradise-webhook'
      preLoaderRoute: typeof ApiPublicParadiseWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-status': {
      id: '/api/public/order-status'
      path: '/api/public/order-status'
      fullPath: '/api/public/order-status'
      preLoaderRoute: typeof ApiPublicOrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-pix': {
      id: '/api/public/create-pix'
      path: '/api/public/create-pix'
      fullPath: '/api/public/create-pix'
      preLoaderRoute: typeof ApiPublicCreatePixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ObrigadoRoute: ObrigadoRoute,
  PixTransactionIdRoute: PixTransactionIdRoute,
  ApiPublicCreatePixRoute: ApiPublicCreatePixRoute,
  ApiPublicOrderStatusRoute: ApiPublicOrderStatusRoute,
  ApiPublicParadiseWebhookRoute: ApiPublicParadiseWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
